version: '3.8'

services:
  nuxt:
    build:
      context: .
    image: e-learning-nuxtapp
    container_name: e-learning-nuxtapp
    command: npm run dev
    volumes:
    - .:/e-learning-nuxtapp
    - /e-learning-nuxtapp/node_modules
    ports:
      - "3000:3000"